# config/rbac/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-tracker-role
rules:
- apiGroups: [""]  # Core API Group
  resources: ["pods", "events", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["ddukbg.k8s"]
  resources: ["resourcetrackers", "resourcetrackers/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]