apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-tracker-role
rules:
- apiGroups: ["ddukbg.k8s"]
  resources: ["deploymenttrackers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["ddukbg.k8s"]
  resources: ["deploymenttrackers/status"]
  verbs: ["get", "update", "patch"]