# config/rbac/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-tracker-role
rules:
- apiGroups: ["ddukbg.k8s"]
  resources: ["resourcetrackers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]  # events 리소스 추가
  verbs: ["create", "patch"]
- apiGroups: ["ddukbg.k8s"]
  resources: ["resourcetrackers/status"]
  verbs: ["get", "update", "patch"]