# config/samples/resource_tracker_statefulset.yaml
apiVersion: ddukbg.k8s/v1alpha1
kind: ResourceTracker
metadata:
  name: mysql-tracker
spec:
  target:
    kind: StatefulSet
    name: mysql
    namespace: default
  notify:
    slack: "https://hooks.slack.com/services/..."

    
---
# 테스트용 StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: default
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0