apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-deploy-watcher.fullname" . }}
  labels:
    {{- include "k8s-deploy-watcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-deploy-watcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-deploy-watcher.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "k8s-deploy-watcher.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
            - name: health
              containerPort: {{ .Values.healthProbe.port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          resources:
            {{- toYaml .Values.resources | nindent 12 }}