apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "deployment-tracker" }}
  namespace: {{ .Values.serviceAccount.namespace | default "default" }}
  labels:
    app: {{ .Chart.Name }}
