apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-deploy-watcher.fullname" . }}
  labels:
    {{- include "k8s-deploy-watcher.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.healthProbe.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "k8s-deploy-watcher.selectorLabels" . | nindent 4 }}