apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: deploymenttrackers.ddukbg
spec:
  group: ddukbg
  names:
    kind: DeploymentTracker
    plural: deploymenttrackers
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              deploymentName:
                type: string
              namespace:
                type: string
              notify:
                type: object
                properties:
                  slack:
                    type: string
                  email:
                    type: string
