name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.1'  # go.mod 버전과 일치하도록 수정
        
    - name: Verify dependencies
      run: |
        go mod verify
        
    - name: Run tests
      run: make test
      
    - name: Build
      run: make build
      
    - name: Run integration tests
      run: |
        make integration-test
        
    - name: Upload test coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: cover.out