name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4    # v2에서 v4로 업그레이드
    
    - name: Set up Go
      uses: actions/setup-go@v5    # v2에서 v5로 업그레이드
      with:
        go-version: '1.16'
        
    - name: Verify dependencies
      run: |
        go mod verify
        
    - name: Run tests
      run: make test
      
    - name: Build
      run: make build
      
    - name: Run integration tests
      run: |
        make integration-test
        
    - name: Upload test coverage
      uses: actions/upload-artifact@v3    # v2에서 v3로 업그레이드
      with:
        name: coverage-report
        path: cover.out