name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    
    - name: Install dependencies
      run: |
        go mod download
        
    - name: Run tests
      run: make test
      
    - name: Build
      run: make build
    
    - name: Run code coverage
      run: |
        go test ./... -coverprofile=coverage.txt -covermode=atomic
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        flags: unittests